import { describe, it, expect } from 'vitest'
import { readFileSync, existsSync } from 'node:fs'
import { resolve } from 'node:path'

/*
The install path fails quietly. A manifest pointing at an icon that is not
there still parses, Chrome still shows a menu entry, and the user still gets a
shortcut — it just opens in a browser tab instead of launching standalone,
which looks like the app was never a PWA rather than like a broken reference.
That is the bug this file exists to catch. Icons are generated by
`scripts/generate-icons.mjs`, so a rename there is exactly how it would happen.
*/

const root = resolve(__dirname, '..')
const viteConfig = readFileSync(resolve(root, 'vite.config.ts'), 'utf8')
const indexHtml = readFileSync(resolve(root, 'index.html'), 'utf8')
const deployScript = readFileSync(resolve(root, 'scripts/deploy.sh'), 'utf8')

const referenced = (source: string) =>
	Array.from(source.matchAll(/icons\/[a-z0-9-]+\.png/g), (m) => m[0])

describe('pwa manifest icons', () => {
	const icons = referenced(viteConfig)

	it('declares icons at all', () => {
		expect(icons.length).toBeGreaterThan(0)
	})

	it.each(icons)('%s exists in public/', (icon) => {
		expect(existsSync(resolve(root, 'public', icon))).toBe(true)
	})

	it('declares the 192px icon Chrome requires to offer a real install', () => {
		expect(icons).toContain('icons/icon-192.png')
		expect(viteConfig).toContain("sizes: '192x192'")
	})

	it('declares a maskable icon so Android does not crop the mark', () => {
		expect(viteConfig).toContain("purpose: 'maskable'")
	})

	it('stays standalone — a display mode of browser is the bug itself', () => {
		expect(viteConfig).toContain("display: 'standalone'")
	})
})

describe('icons referenced from index.html', () => {
	it.each(referenced(indexHtml))('%s exists in public/', (icon) => {
		expect(existsSync(resolve(root, 'public', icon))).toBe(true)
	})
})

describe('deploy caching', () => {
	/*
	These are the only build outputs without a content hash in the filename. A
	service worker pinned at the edge for a year is the worst thing this CDN
	could do, since it would keep serving an old precache manifest to an
	already-installed app.
	*/
	it.each(['sw.js', 'registerSW.js', 'manifest.webmanifest', 'index.html'])(
		'%s is on the never-cache list in scripts/deploy.sh',
		(file) => {
			expect(deployScript).toContain(file)
		},
	)
})
